[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oarc"
version = "0.1.0"
description = "OARC: a versatile Python package that streamlines audio processing, web API development, machine learning workflows, and speech interfaces to empower rapid prototyping and seamless integration of AI-driven functionalities."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "OARC Team"}
]
dependencies = [
    # Build tools
    "build",
    "setuptools>=45", 
    "wheel",
    
    # Core libraries
    "cython>=0.30.0",
    "numpy>=1.24.3",
    "scipy>=1.13.0",
    
    # Audio processing
    "librosa>=0.11.0",
    "sounddevice>=0.5.1",
    "soundfile>=0.12.0",
    
    # Web & API
    "fastapi>=0.68.0",
    "gradio>=5.23.1",
    "pydantic>=1.8.0",
    "python-multipart>=0.0.5",
    "requests>=2.26.0",
    "uvicorn>=0.15.0",
    "websockets>=10.0",
    
    # Machine Learning
    "llama-index>=0.12.26",
    "llama-index-experimental>=0.5.4",
    "ollama>=0.4.7",
    "transformers>=4.47.0",
    
    # Speech
    "openai-whisper>=20240930",
    "SpeechRecognition>=3.8.1",
    
    # TTS dependencies
    "anyascii>=0.3.0",
    "encodec>=0.1.1",
    "einops>=0.6.0",
    "inflect>=5.6.0",
    "num2words>=0.5.14",
    "pysbd>=0.3.4",
    "tqdm>=4.64.1",
    
    # Utilities
    "fsspec[http]>=2023.6.0",
    "keyboard>=0.13.5",
    "matplotlib>=3.8.4",
    "packaging>=23.1",
    "pandas>=1.3.0",
    "pyyaml>=6.0",
    "typing_extensions>=4.10",
]

[project.optional-dependencies]
dev = [
    # Testing & code quality
    "black",
    "coverage[toml]>=7",
    "flake8",
    "pre-commit>=4",
    "pytest>=8",
    "ruff==0.9.1",
    "twine",
    
    # Documentation
    "furo>=2024.8.6",
    "sphinx==7.4.7",
    "sphinx_copybutton>=0.5.2",
    
    # Additional tools
    "bokeh>=3.0.3",
    "umap-learn>=0.5.1",
]

[project.scripts]
oarc = "oarc.main:main"

[tool.setuptools]
packages = ["oarc"]
package-dir = {"" = "."}
