[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oarc"
version = "0.1.0"
description = "Ollama Agent Roll Cage - Speech to Speech with Vision AI Chatbot API"
readme = "README.md"
authors = [{name = "Leo Borcherding"}]
# Update license to Apache 2.0
license = {text = "Apache License 2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
]
keywords = ["speech", "ai", "chatbot", "vision", "ollama"]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.68.0",
    "keyboard>=0.13.5",
    "numpy>=1.19.0",
    "ollama>=0.1.0",
    "pandas>=1.3.0",
    "python-multipart>=0.0.5",
    "pyaudio>=0.2.11",
    "pydantic>=1.8.0",
    "requests>=2.26.0",
    "SpeechRecognition>=3.8.1",
    "torch>=1.9.0",
    "transformers>=4.0.0",
    "uvicorn>=0.15.0",
    "websockets>=10.0",
    "whisper>=1.0",
    "cython>=0.30.0",
]

[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest",
    "black",
    "flake8",
]