[build-system]
requires = [
    "setuptools>=70.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "oarc"
version = "0.1.0"
description = "OARC: a versatile Python package that streamlines audio processing, web API development, machine learning workflows, and speech interfaces to empower rapid prototyping and seamless integration of AI-driven functionalities."
readme = "README.md"
requires-python = ">=3.10,<3.12"
authors = [
    { name = "OARC Team" },
]
dependencies = [
    "aiofiles>=23.2.1",
    "albumentations>=2.0.5",
    "anyascii>=0.3.2",
    "bokeh>=3.7.2",
    "build>=1.2.2.post1",
    "comet>=3.1.0",
    "coremltools>=8; platform_system != 'Windows' and python_version <= '3.12'",
    "crawl4ai>=0.3.731",
    "cython>=3.0.12",
    "dataset>=1.6.2",
    "dvclive>=3.48.2",
    "duckduckgo-search>=2025.4.4",
    "einops>=0.8.1",
    "encodec>=0.1.1",
    "fastapi>=0.115.12",
    "flatbuffers>=25.2.10; platform_machine == 'aarch64'",
    "fsspec[http]>=2025.3.2",
    "gtts>=2.5.4",
    "gradio>=5.23.3",
    "h5py>=3.13.0; platform_machine == 'aarch64'",
    "huggingface-hub>=0.30.1",
    "hub-sdk>=0.0.20",
    "inflect>=7.5.0",
    "ipython>=8.34.0",
    "keyboard>=0.13.5",
    "librosa>=0.11.0",
    "llama-index>=0.12.28",
    "matplotlib>=3.10.1",
    "num2words>=0.5.14",
    "numpy>=1.26.4",
    "ollama>=0.4.7",
    "onnx>=1.17.0",
    "openai>=1.70.0",
    "opencv-python>=4.11.0.86",
    "openvino>=2025.0.0",
    "packaging>=23.2",
    "pandas>=2.2.3",
    "pygame>=2.6.1",
    "pycocotools>=2.0.8",
    "py-cpuinfo>=9.0.0",
    "pydantic>=2.11.2",
    "pyqt6>=6.8.1",
    "pyvirtualcam>=0.12.1",
    "pywin32>=310; platform_system == 'Windows'",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "setuptools>=78.1.0",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1",
    "speechrecognition>=3.14.2",
    "streamlit>=1.44.1",
    "tensorboard>=2.15.2",
    "tensorflow>=2.15.1",
    "tensorflowjs>=4.22.0",
    "tensorstore>=0.1.73; platform_machine == 'aarch64' and python_version >= '3.9'",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
    "transformers>=4.50.3",
    "typing_extensions>=4.13.1",
    "ultralytics>=8.3.102",
    "uv>=0.6.12",
    "websockets>=15.0.1",
    "wheel>=0.45.1",
]

[project.optional-dependencies]
dev = [
    "black",
    "coverage[toml]>=7",
    "flake8",
    "furo>=2024.8.6",
    "packaging>=23.0; python_version < '3.12'",
    "pre-commit>=4",
    "pytest>=8",
    "ruff>=0.9.3",
    "sphinx==7.4.7; python_version < '3.12'",
    "sphinx_copybutton>=0.5.2",
    "tomli",
    "tomli_w>=1.2.0",
    "twine",
]

[project.scripts]
oarc = "oarc.main:main"

[tool.setuptools]
packages = [
    "oarc",
]

[tool.setuptools.package-dir]
"" = "."
