[build-system]
requires = ["setuptools>=70.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oarc"
version = "0.1.0"
description = "OARC: a versatile Python package that streamlines audio processing, web API development, machine learning workflows, and speech interfaces to empower rapid prototyping and seamless integration of AI-driven functionalities."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "OARC Team"}
]
dependencies = [
    # Core libraries
    "cython>=0.30.0",
    "scipy>=1.13.0",
    "numpy>=1.24.3",
    "pywin32>=305; platform_system == 'Windows'",
    "aiofiles>=22.0,<24.0",

    # Database
    "pymongo>=4.11.3",

    # Machine Learning
    "ollama>=0.4.7",
    "llama-index-experimental>=0.5.4",
    "llama-index>=0.12.26",
    "transformers>=4.47.0",
    "scikit-learn>=1.3.2",
    "bokeh>=3.0.3",
    "umap-learn>=0.5.1",

    # Additional YOLO core dependencies
    "py-cpuinfo",
    "psutil",
    "seaborn>=0.11.0",
    "ultralytics-thop>=2.0.0",
    "torchvision>=0.9.0",
    "torch>=1.8.0",
    "pycocotools>=2.0.7",
    "albumentations>=1.4.6",

    # Vision processing
    "ultralytics>=8.3.98",
    "opencv-python>=4.11.0.86",
    "pyvirtualcam>=0.12.1",

    # Audio processing
    "sounddevice>=0.5.1",
    "soundfile>=0.12.0",
    "librosa>=0.11.0",

    # Speech processing
    "SpeechRecognition>=3.8.1",
    "openai-whisper>=20240930",

    # Web & API
    "requests>=2.26.0",
    "python-multipart>=0.0.5",
    "pydantic>=1.8.0",
    "websockets>=10.0",
    "uvicorn>=0.15.0",
    "fastapi>=0.68.0",
    "gradio>=5.23.1",
    "duckduckgo-search>=7.5.5",
    "Crawl4AI>=0.3.8",

    # TTS dependencies
    "gTTS>=2.5.4",
    "tqdm>=4.64.1",
    "anyascii>=0.3.0",
    "pysbd>=0.3.4",
    "num2words>=0.5.14",
    "inflect>=5.6.0",
    "einops>=0.6.0",
    "encodec>=0.1.1",

    # Interactive tools
    "pygame>=2.6.1",
    "PyQt5>=5.15.11",
    "ipython",

    # Utilities
    "typing_extensions>=4.10",
    "pyyaml>=6.0",
    "pandas>=1.3.0",
    "packaging>=23.1",
    "matplotlib>=3.8.4",
    "keyboard>=0.13.5",
    "fsspec[http]>=2023.6.0",
    "streamlit",
    "tensorboard>=2.13.0",

    # Build tools
    "wheel",
    "setuptools>=45",
    "build",
    "onnx>=1.12.0",
    "tensorflow>=2.0.0",
    "tensorflowjs>=4.0.0",
    
    # YOLO export dependencies (moved from dev)
    "openvino>=2024.0.0,!=2025.0.0",
    "h5py!=3.11.0; platform_machine == 'aarch64'",
    "flatbuffers>=23.5.26,<100; platform_machine == 'aarch64'",
    "coremltools>=8.0; platform_system != 'Windows' and python_version <= '3.12'",
    "tensorstore>=0.1.63; platform_machine == 'aarch64' and python_version >= '3.9'",
    
    # YOLO logging dependencies (moved from dev)
    "comet",
    "dvclive>=2.12.0",
    
    # YOLO extra dependencies (moved from dev)
    "hub-sdk>=0.0.12",
]

[project.optional-dependencies]
dev = [
    # Testing & code quality
    "black",
    "twine",
    "flake8",
    "pytest>=8.0.0",
    "ruff>=0.9.3",
    "pre-commit>=4",
    "coverage[toml]>=7",
    
    # Documentation
    "sphinx==7.4.7",
    "furo>=2024.8.6",
    "sphinx_copybutton>=0.5.2",
]

[project.scripts]
oarc = "oarc.main:main"

[tool.setuptools]
packages = ["oarc"]
package-dir = {"" = "."}
