[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oarc"
version = "0.1.0"
description = "Ollama Agent Roll Cage - Speech to Speech with Vision AI Chatbot API"
readme = "README.md"
authors = [{name = "Leo Borcherding"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
keywords = ["speech", "ai", "chatbot", "vision", "ollama"]
dependencies = [
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "pandas>=1.3.0",
    "torch>=1.9.0",
    "transformers>=4.0.0",
    "TTS>=0.8.0",
    "SpeechRecognition>=3.8.1",
    "ollama>=0.1.0",
    "whisper>=1.0",
    "websockets>=10.0",
]