[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oarc"
version = "0.1.0"
description = "Ollama Agent Roll Cage - Speech to Speech with Vision AI Chatbot API"
readme = "README.md"
authors = [{name = "Leo Borcherding"}]
license = {text = "Apache License 2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
]
keywords = ["speech", "ai", "chatbot", "vision", "ollama"]
requires-python = ">=3.10"
# Minimal dependencies to avoid installation issues
dependencies = [
    "setuptools>=45",
    "wheel",
]

[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest",
    "black",
    "flake8",
]

[tool.setuptools]
packages = ["oarc"]

[tool.setuptools.package-data]
oarc = ["config_files/*.ini"]
